syntax = "proto3";
package Protocol;


enum PacketId {
    PKT_NONE = 0;
    PKT_CS_LOGIN = 1;         
    PKT_SC_LOGIN_OK = 2;      
    PKT_CS_CHAT = 3;          
    PKT_SC_CHAT_BROADCAST = 4; 
    PKT_SC_WHISPER = 5;           
    PKT_CS_WHISPER = 6;         
    PKT_CS_MOVING = 7;           
    PKT_SC_MOVING = 8;
    PKT_CS_ENTER_GAME = 9;
    PKT_SC_ENTER_GAME = 10;
    PKT_SC_PLAYER_SPAWN = 11; 
    PKT_CS_GAME_READY = 12;
    PKT_SC_DESPAWN = 13;

}


message CS_LOGIN {
    uint64 user_id = 1;
    string password = 2;
}


message SC_LOGIN_OK {
    bool success = 1;
    uint64 player_id = 2; 
    
}


message CS_CHAT {
    string msg = 1;
}


message SC_CHAT_BROADCAST {
    uint64 player_id = 1;
    string msg = 2;
}


message SC_WHISPER {
    uint64 fromplayer_id = 1;   
    string msg = 2;      
}


message CS_WHISPER  
{
    uint64 targetplayer_id = 1;
    string msg = 2;
}

message PosInfo {
  uint64 object_id = 1; // 이동하는 대상의 ID
  float x = 2;
  float y = 3;
  float z = 4;
  float yaw = 5;       // 바라보는 방향 (회전)
  uint64 templeteId = 6;
  uint64 state = 7;
}

message StatInfo {
    uint64 object_id = 1;
    string name = 2;
    uint64 hp = 3;
    uint64 attack = 4;
    uint64 speed = 5;
    uint64 level = 6;
}
message CS_MOVING {
    PosInfo pos_info = 1;
}


message SC_MOVING {
    PosInfo pos_info = 1;
}

message CS_ENTER_GAME {

}

message SC_ENTER_GAME {
    PosInfo pos_info = 1;
}

message SC_PLAYER_SPAWN {
    repeated PosInfo players_pos_info = 1;
    
}

message CS_GAME_READY {
    uint64 player_id = 1;
}

message SC_DESPAWN {
    repeated uint64 player_id = 1;
}