syntax = "proto3";
package Protocol;


enum PacketId {
    PKT_NONE = 0;
    PKT_CS_LOGIN = 1;         
    PKT_SC_LOGIN_OK = 2;      
    PKT_CS_CHAT = 3;          
    PKT_SC_CHAT_BROADCAST = 4; 
    PKT_SC_WHISPER = 5;           
    PKT_CS_WHISPER = 6;         
    PKT_CS_MOVING = 7;           
    PKT_SC_MOVING = 8;
    PKT_CS_ENTER_GAME = 9;
    PKT_SC_ENTER_GAME = 10;
    PKT_SC_PLAYER_SPAWN = 11; 
    PKT_CS_GAME_READY = 12;
    PKT_SC_PLAYER_DESPAWN = 13;
    PKT_CS_SKILL = 14;
    PKT_SC_SKILL = 15;
    PKT_SC_CHANGE_HP = 16;
    PKT_SC_CHANGE_MP = 17;
    PKT_SC_MONSTER_SPAWN = 18;
    PKT_SC_MONSTER_DEAD = 19;
    PKT_CS_OWNED_ITEM_REQUEST = 20;
    PKT_SC_ITEM_RESPONSE = 21;
    
}


message CS_LOGIN {
    int32 user_id = 1;
    string password = 2;
}


message SC_LOGIN_OK {
    bool success = 1;
    int32 player_id = 2; 
    
}


message CS_CHAT {
    string msg = 1;
}


message SC_CHAT_BROADCAST {
    int32 player_id = 1;
    string msg = 2;
}


message SC_WHISPER {
    int32 fromplayer_id = 1;   
    string msg = 2;      
}


message CS_WHISPER  
{
    int32 targetplayer_id = 1;
    string msg = 2;
}

message PosInfo {
  int32 object_id = 1; // 이동하는 대상의 ID
  float x = 2;
  float y = 3;
  float z = 4;
  float yaw = 5;       // 바라보는 방향 (회전)
  int32 state = 6;
}

message StatInfo {
    int32 object_id = 1;
    string name = 2;
    int32 hp = 3;
    int32 attack = 4;
    int32 speed = 5;
    int32 level = 6;
}
message CS_MOVING {
    PosInfo pos_info = 1;
}


message SC_MOVING {
    repeated PosInfo pos_info = 1;
}

message CS_ENTER_GAME {

}

message SC_ENTER_GAME {
    PosInfo pos_info = 1;
    int32 templateId = 2;
    int32 MapId = 3;
}

message SC_PLAYER_SPAWN {
    repeated SpawnInfo players_spawn_info = 1;
    
}

message SpawnInfo
{
    PosInfo spawnposinfo = 1;
    int32 templateId = 2;
}

message CS_GAME_READY {
    int32 player_id = 1;
}

message SC_PLAYER_DESPAWN  {
    repeated int32 player_id = 1;
}

message CS_SKILL {
    int32 skill_id = 1;

  // 스킬 타입별로 필요한 '추가 정보'만 묶어서 관리
  oneof extra_info {
    TargetobjectInfo target = 2;      // 근접/타겟팅용 (대상 ID)
    TargetPosInfo dest_pos = 3;  // 논타겟/이동기용 (목표 좌표)
  }
}

message SC_SKILL {
  int32 object_id = 1;
  int32 skill_id = 2;
  oneof extra_info {
    TargetobjectInfo target = 3; // 근접/타겟팅용 (대상 ID)
    TargetPosInfo dest_pos = 4;  // 논타겟/이동기용 (목표 좌표)
  }
}

message SC_CHANGE_HP {
  int32 object_id = 1;
  int32 current_hp = 2;
  int32 damage = 3;
  int32 attacker_id = 4;
}


message TargetobjectInfo {
    int32 target_object_id = 1;
}

message TargetPosInfo{
    float x = 1;
    float y = 2;
    float z = 3;
}

message SC_CHANGE_MP {
  int32 object_id = 1;
  int32 current_mp = 2;
  
}

message SC_MONSTER_SPAWN {
    repeated SpawnInfo monsters_spawn_info = 1;
}

message SC_MONSTER_DEAD {
    repeated int32 dead_object_id_list = 1;
}

message CS_OWNED_ITEM_REQUEST {
    int32 player_id = 1; //자기 자신의 objectID(playerId)를 확인용으로 전송
}

message SC_ITEM_RESPONSE {
    repeated ItemInfo items = 1;
}

message ItemInfo 
{
    int32 Dbid = 1; 
    int32 TemplateId = 2;
    int32 Count = 3;
    int32 Slot = 4;
    string item_memo = 5;
}

