// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocol.proto
// Protobuf C++ Version: 5.29.5

#include "Protocol.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace Protocol {

inline constexpr SC_WHISPER::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        fromplayerid_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SC_WHISPER::SC_WHISPER(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_WHISPERDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_WHISPERDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_WHISPERDefaultTypeInternal() {}
  union {
    SC_WHISPER _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_WHISPERDefaultTypeInternal _SC_WHISPER_default_instance_;

inline constexpr SC_LOGIN_OK::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : playerguid_{::uint64_t{0u}},
        success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SC_LOGIN_OK::SC_LOGIN_OK(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_LOGIN_OKDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_LOGIN_OKDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_LOGIN_OKDefaultTypeInternal() {}
  union {
    SC_LOGIN_OK _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_LOGIN_OKDefaultTypeInternal _SC_LOGIN_OK_default_instance_;

inline constexpr SC_CHAT_BROADCAST::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        playerid_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SC_CHAT_BROADCAST::SC_CHAT_BROADCAST(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SC_CHAT_BROADCASTDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SC_CHAT_BROADCASTDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SC_CHAT_BROADCASTDefaultTypeInternal() {}
  union {
    SC_CHAT_BROADCAST _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SC_CHAT_BROADCASTDefaultTypeInternal _SC_CHAT_BROADCAST_default_instance_;

inline constexpr CS_WHISPER::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        targetplayerid_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CS_WHISPER::CS_WHISPER(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CS_WHISPERDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_WHISPERDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_WHISPERDefaultTypeInternal() {}
  union {
    CS_WHISPER _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_WHISPERDefaultTypeInternal _CS_WHISPER_default_instance_;

inline constexpr CS_LOGIN::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : userid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CS_LOGIN::CS_LOGIN(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CS_LOGINDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_LOGINDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_LOGINDefaultTypeInternal() {}
  union {
    CS_LOGIN _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_LOGINDefaultTypeInternal _CS_LOGIN_default_instance_;

inline constexpr CS_CHAT::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CS_CHAT::CS_CHAT(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CS_CHATDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CS_CHATDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CS_CHATDefaultTypeInternal() {}
  union {
    CS_CHAT _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CS_CHATDefaultTypeInternal _CS_CHAT_default_instance_;
}  // namespace Protocol
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_Protocol_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_Protocol_2eproto = nullptr;
const ::uint32_t
    TableStruct_Protocol_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_LOGIN, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_LOGIN, _impl_.userid_),
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_LOGIN, _impl_.password_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_LOGIN_OK, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_LOGIN_OK, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_LOGIN_OK, _impl_.playerguid_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_CHAT, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_CHAT, _impl_.msg_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_CHAT_BROADCAST, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_CHAT_BROADCAST, _impl_.playerid_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_CHAT_BROADCAST, _impl_.msg_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_WHISPER, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_WHISPER, _impl_.fromplayerid_),
        PROTOBUF_FIELD_OFFSET(::Protocol::SC_WHISPER, _impl_.msg_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_WHISPER, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_WHISPER, _impl_.targetplayerid_),
        PROTOBUF_FIELD_OFFSET(::Protocol::CS_WHISPER, _impl_.msg_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Protocol::CS_LOGIN)},
        {10, -1, -1, sizeof(::Protocol::SC_LOGIN_OK)},
        {20, -1, -1, sizeof(::Protocol::CS_CHAT)},
        {29, -1, -1, sizeof(::Protocol::SC_CHAT_BROADCAST)},
        {39, -1, -1, sizeof(::Protocol::SC_WHISPER)},
        {49, -1, -1, sizeof(::Protocol::CS_WHISPER)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::Protocol::_CS_LOGIN_default_instance_._instance,
    &::Protocol::_SC_LOGIN_OK_default_instance_._instance,
    &::Protocol::_CS_CHAT_default_instance_._instance,
    &::Protocol::_SC_CHAT_BROADCAST_default_instance_._instance,
    &::Protocol::_SC_WHISPER_default_instance_._instance,
    &::Protocol::_CS_WHISPER_default_instance_._instance,
};
const char descriptor_table_protodef_Protocol_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016Protocol.proto\022\010Protocol\",\n\010CS_LOGIN\022\016"
    "\n\006userId\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"2\n\013SC_L"
    "OGIN_OK\022\017\n\007success\030\001 \001(\010\022\022\n\nplayerGuid\030\002"
    " \001(\004\"\026\n\007CS_CHAT\022\013\n\003msg\030\001 \001(\t\"2\n\021SC_CHAT_"
    "BROADCAST\022\020\n\010playerId\030\001 \001(\004\022\013\n\003msg\030\002 \001(\t"
    "\"/\n\nSC_WHISPER\022\024\n\014fromplayerId\030\001 \001(\004\022\013\n\003"
    "msg\030\002 \001(\t\"1\n\nCS_WHISPER\022\026\n\016targetplayerI"
    "d\030\001 \001(\004\022\013\n\003msg\030\002 \001(\t*\223\001\n\010PacketId\022\014\n\010PKT"
    "_NONE\020\000\022\020\n\014PKT_CS_LOGIN\020\001\022\023\n\017PKT_SC_LOGI"
    "N_OK\020\002\022\017\n\013PKT_CS_CHAT\020\003\022\031\n\025PKT_SC_CHAT_B"
    "ROADCAST\020\004\022\022\n\016PKT_SC_WHISPER\020\005\022\022\n\016PKT_CS"
    "_WHISPER\020\006b\006proto3"
};
static ::absl::once_flag descriptor_table_Protocol_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_Protocol_2eproto = {
    false,
    false,
    458,
    descriptor_table_protodef_Protocol_2eproto,
    "Protocol.proto",
    &descriptor_table_Protocol_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_Protocol_2eproto::offsets,
    file_level_enum_descriptors_Protocol_2eproto,
    file_level_service_descriptors_Protocol_2eproto,
};
namespace Protocol {
const ::google::protobuf::EnumDescriptor* PacketId_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_Protocol_2eproto);
  return file_level_enum_descriptors_Protocol_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PacketId_internal_data_[] = {
    458752u, 0u, };
bool PacketId_IsValid(int value) {
  return 0 <= value && value <= 6;
}
// ===================================================================

class CS_LOGIN::_Internal {
 public:
};

CS_LOGIN::CS_LOGIN(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_LOGIN)
}
inline PROTOBUF_NDEBUG_INLINE CS_LOGIN::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::CS_LOGIN& from_msg)
      : userid_(arena, from.userid_),
        password_(arena, from.password_),
        _cached_size_{0} {}

CS_LOGIN::CS_LOGIN(
    ::google::protobuf::Arena* arena,
    const CS_LOGIN& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CS_LOGIN* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Protocol.CS_LOGIN)
}
inline PROTOBUF_NDEBUG_INLINE CS_LOGIN::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : userid_(arena),
        password_(arena),
        _cached_size_{0} {}

inline void CS_LOGIN::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CS_LOGIN::~CS_LOGIN() {
  // @@protoc_insertion_point(destructor:Protocol.CS_LOGIN)
  SharedDtor(*this);
}
inline void CS_LOGIN::SharedDtor(MessageLite& self) {
  CS_LOGIN& this_ = static_cast<CS_LOGIN&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.userid_.Destroy();
  this_._impl_.password_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CS_LOGIN::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CS_LOGIN(arena);
}
constexpr auto CS_LOGIN::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CS_LOGIN),
                                            alignof(CS_LOGIN));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CS_LOGIN::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CS_LOGIN_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CS_LOGIN::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CS_LOGIN>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CS_LOGIN::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CS_LOGIN>(), &CS_LOGIN::ByteSizeLong,
            &CS_LOGIN::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_._cached_size_),
        false,
    },
    &CS_LOGIN::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CS_LOGIN::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 40, 2> CS_LOGIN::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::CS_LOGIN>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string password = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_.password_)}},
    // string userId = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_.userid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string userId = 1;
    {PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_.userid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string password = 2;
    {PROTOBUF_FIELD_OFFSET(CS_LOGIN, _impl_.password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\6\10\0\0\0\0\0"
    "Protocol.CS_LOGIN"
    "userId"
    "password"
  }},
};

PROTOBUF_NOINLINE void CS_LOGIN::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CS_LOGIN)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.userid_.ClearToEmpty();
  _impl_.password_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CS_LOGIN::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CS_LOGIN& this_ = static_cast<const CS_LOGIN&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CS_LOGIN::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CS_LOGIN& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.CS_LOGIN)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string userId = 1;
          if (!this_._internal_userid().empty()) {
            const std::string& _s = this_._internal_userid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.CS_LOGIN.userId");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string password = 2;
          if (!this_._internal_password().empty()) {
            const std::string& _s = this_._internal_password();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.CS_LOGIN.password");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.CS_LOGIN)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CS_LOGIN::ByteSizeLong(const MessageLite& base) {
          const CS_LOGIN& this_ = static_cast<const CS_LOGIN&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CS_LOGIN::ByteSizeLong() const {
          const CS_LOGIN& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.CS_LOGIN)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string userId = 1;
            if (!this_._internal_userid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_userid());
            }
            // string password = 2;
            if (!this_._internal_password().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_password());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CS_LOGIN::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CS_LOGIN*>(&to_msg);
  auto& from = static_cast<const CS_LOGIN&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CS_LOGIN)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_userid().empty()) {
    _this->_internal_set_userid(from._internal_userid());
  }
  if (!from._internal_password().empty()) {
    _this->_internal_set_password(from._internal_password());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CS_LOGIN::CopyFrom(const CS_LOGIN& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CS_LOGIN)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CS_LOGIN::InternalSwap(CS_LOGIN* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.userid_, &other->_impl_.userid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
}

::google::protobuf::Metadata CS_LOGIN::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_LOGIN_OK::_Internal {
 public:
};

SC_LOGIN_OK::SC_LOGIN_OK(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_LOGIN_OK)
}
SC_LOGIN_OK::SC_LOGIN_OK(
    ::google::protobuf::Arena* arena, const SC_LOGIN_OK& from)
    : SC_LOGIN_OK(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SC_LOGIN_OK::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SC_LOGIN_OK::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, playerguid_),
           0,
           offsetof(Impl_, success_) -
               offsetof(Impl_, playerguid_) +
               sizeof(Impl_::success_));
}
SC_LOGIN_OK::~SC_LOGIN_OK() {
  // @@protoc_insertion_point(destructor:Protocol.SC_LOGIN_OK)
  SharedDtor(*this);
}
inline void SC_LOGIN_OK::SharedDtor(MessageLite& self) {
  SC_LOGIN_OK& this_ = static_cast<SC_LOGIN_OK&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SC_LOGIN_OK::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SC_LOGIN_OK(arena);
}
constexpr auto SC_LOGIN_OK::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SC_LOGIN_OK),
                                            alignof(SC_LOGIN_OK));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SC_LOGIN_OK::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SC_LOGIN_OK_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SC_LOGIN_OK::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SC_LOGIN_OK>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SC_LOGIN_OK::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SC_LOGIN_OK>(), &SC_LOGIN_OK::ByteSizeLong,
            &SC_LOGIN_OK::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_._cached_size_),
        false,
    },
    &SC_LOGIN_OK::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SC_LOGIN_OK::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> SC_LOGIN_OK::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SC_LOGIN_OK>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint64 playerGuid = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SC_LOGIN_OK, _impl_.playerguid_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.playerguid_)}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SC_LOGIN_OK, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // uint64 playerGuid = 2;
    {PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.playerguid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SC_LOGIN_OK::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SC_LOGIN_OK)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.playerguid_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.success_) -
      reinterpret_cast<char*>(&_impl_.playerguid_)) + sizeof(_impl_.success_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SC_LOGIN_OK::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SC_LOGIN_OK& this_ = static_cast<const SC_LOGIN_OK&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SC_LOGIN_OK::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SC_LOGIN_OK& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.SC_LOGIN_OK)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool success = 1;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_success(), target);
          }

          // uint64 playerGuid = 2;
          if (this_._internal_playerguid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                2, this_._internal_playerguid(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.SC_LOGIN_OK)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SC_LOGIN_OK::ByteSizeLong(const MessageLite& base) {
          const SC_LOGIN_OK& this_ = static_cast<const SC_LOGIN_OK&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SC_LOGIN_OK::ByteSizeLong() const {
          const SC_LOGIN_OK& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.SC_LOGIN_OK)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // uint64 playerGuid = 2;
            if (this_._internal_playerguid() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_playerguid());
            }
            // bool success = 1;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SC_LOGIN_OK::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SC_LOGIN_OK*>(&to_msg);
  auto& from = static_cast<const SC_LOGIN_OK&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SC_LOGIN_OK)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_playerguid() != 0) {
    _this->_impl_.playerguid_ = from._impl_.playerguid_;
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SC_LOGIN_OK::CopyFrom(const SC_LOGIN_OK& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SC_LOGIN_OK)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_LOGIN_OK::InternalSwap(SC_LOGIN_OK* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.success_)
      + sizeof(SC_LOGIN_OK::_impl_.success_)
      - PROTOBUF_FIELD_OFFSET(SC_LOGIN_OK, _impl_.playerguid_)>(
          reinterpret_cast<char*>(&_impl_.playerguid_),
          reinterpret_cast<char*>(&other->_impl_.playerguid_));
}

::google::protobuf::Metadata SC_LOGIN_OK::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CS_CHAT::_Internal {
 public:
};

CS_CHAT::CS_CHAT(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_CHAT)
}
inline PROTOBUF_NDEBUG_INLINE CS_CHAT::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::CS_CHAT& from_msg)
      : msg_(arena, from.msg_),
        _cached_size_{0} {}

CS_CHAT::CS_CHAT(
    ::google::protobuf::Arena* arena,
    const CS_CHAT& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CS_CHAT* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:Protocol.CS_CHAT)
}
inline PROTOBUF_NDEBUG_INLINE CS_CHAT::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msg_(arena),
        _cached_size_{0} {}

inline void CS_CHAT::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CS_CHAT::~CS_CHAT() {
  // @@protoc_insertion_point(destructor:Protocol.CS_CHAT)
  SharedDtor(*this);
}
inline void CS_CHAT::SharedDtor(MessageLite& self) {
  CS_CHAT& this_ = static_cast<CS_CHAT&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.msg_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CS_CHAT::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CS_CHAT(arena);
}
constexpr auto CS_CHAT::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CS_CHAT),
                                            alignof(CS_CHAT));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CS_CHAT::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CS_CHAT_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CS_CHAT::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CS_CHAT>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CS_CHAT::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CS_CHAT>(), &CS_CHAT::ByteSizeLong,
            &CS_CHAT::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CS_CHAT, _impl_._cached_size_),
        false,
    },
    &CS_CHAT::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CS_CHAT::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 28, 2> CS_CHAT::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::CS_CHAT>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string msg = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CS_CHAT, _impl_.msg_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string msg = 1;
    {PROTOBUF_FIELD_OFFSET(CS_CHAT, _impl_.msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\3\0\0\0\0\0\0"
    "Protocol.CS_CHAT"
    "msg"
  }},
};

PROTOBUF_NOINLINE void CS_CHAT::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CS_CHAT)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CS_CHAT::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CS_CHAT& this_ = static_cast<const CS_CHAT&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CS_CHAT::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CS_CHAT& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.CS_CHAT)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string msg = 1;
          if (!this_._internal_msg().empty()) {
            const std::string& _s = this_._internal_msg();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.CS_CHAT.msg");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.CS_CHAT)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CS_CHAT::ByteSizeLong(const MessageLite& base) {
          const CS_CHAT& this_ = static_cast<const CS_CHAT&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CS_CHAT::ByteSizeLong() const {
          const CS_CHAT& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.CS_CHAT)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string msg = 1;
            if (!this_._internal_msg().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_msg());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CS_CHAT::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CS_CHAT*>(&to_msg);
  auto& from = static_cast<const CS_CHAT&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CS_CHAT)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CS_CHAT::CopyFrom(const CS_CHAT& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CS_CHAT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CS_CHAT::InternalSwap(CS_CHAT* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
}

::google::protobuf::Metadata CS_CHAT::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_CHAT_BROADCAST::_Internal {
 public:
};

SC_CHAT_BROADCAST::SC_CHAT_BROADCAST(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_CHAT_BROADCAST)
}
inline PROTOBUF_NDEBUG_INLINE SC_CHAT_BROADCAST::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::SC_CHAT_BROADCAST& from_msg)
      : msg_(arena, from.msg_),
        _cached_size_{0} {}

SC_CHAT_BROADCAST::SC_CHAT_BROADCAST(
    ::google::protobuf::Arena* arena,
    const SC_CHAT_BROADCAST& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SC_CHAT_BROADCAST* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.playerid_ = from._impl_.playerid_;

  // @@protoc_insertion_point(copy_constructor:Protocol.SC_CHAT_BROADCAST)
}
inline PROTOBUF_NDEBUG_INLINE SC_CHAT_BROADCAST::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msg_(arena),
        _cached_size_{0} {}

inline void SC_CHAT_BROADCAST::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.playerid_ = {};
}
SC_CHAT_BROADCAST::~SC_CHAT_BROADCAST() {
  // @@protoc_insertion_point(destructor:Protocol.SC_CHAT_BROADCAST)
  SharedDtor(*this);
}
inline void SC_CHAT_BROADCAST::SharedDtor(MessageLite& self) {
  SC_CHAT_BROADCAST& this_ = static_cast<SC_CHAT_BROADCAST&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.msg_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SC_CHAT_BROADCAST::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SC_CHAT_BROADCAST(arena);
}
constexpr auto SC_CHAT_BROADCAST::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SC_CHAT_BROADCAST),
                                            alignof(SC_CHAT_BROADCAST));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SC_CHAT_BROADCAST::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SC_CHAT_BROADCAST_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SC_CHAT_BROADCAST::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SC_CHAT_BROADCAST>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SC_CHAT_BROADCAST::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SC_CHAT_BROADCAST>(), &SC_CHAT_BROADCAST::ByteSizeLong,
            &SC_CHAT_BROADCAST::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SC_CHAT_BROADCAST, _impl_._cached_size_),
        false,
    },
    &SC_CHAT_BROADCAST::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SC_CHAT_BROADCAST::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 38, 2> SC_CHAT_BROADCAST::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SC_CHAT_BROADCAST>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SC_CHAT_BROADCAST, _impl_.msg_)}},
    // uint64 playerId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SC_CHAT_BROADCAST, _impl_.playerid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SC_CHAT_BROADCAST, _impl_.playerid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 playerId = 1;
    {PROTOBUF_FIELD_OFFSET(SC_CHAT_BROADCAST, _impl_.playerid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string msg = 2;
    {PROTOBUF_FIELD_OFFSET(SC_CHAT_BROADCAST, _impl_.msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\0\3\0\0\0\0\0"
    "Protocol.SC_CHAT_BROADCAST"
    "msg"
  }},
};

PROTOBUF_NOINLINE void SC_CHAT_BROADCAST::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SC_CHAT_BROADCAST)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _impl_.playerid_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SC_CHAT_BROADCAST::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SC_CHAT_BROADCAST& this_ = static_cast<const SC_CHAT_BROADCAST&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SC_CHAT_BROADCAST::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SC_CHAT_BROADCAST& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.SC_CHAT_BROADCAST)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 playerId = 1;
          if (this_._internal_playerid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_playerid(), target);
          }

          // string msg = 2;
          if (!this_._internal_msg().empty()) {
            const std::string& _s = this_._internal_msg();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.SC_CHAT_BROADCAST.msg");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.SC_CHAT_BROADCAST)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SC_CHAT_BROADCAST::ByteSizeLong(const MessageLite& base) {
          const SC_CHAT_BROADCAST& this_ = static_cast<const SC_CHAT_BROADCAST&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SC_CHAT_BROADCAST::ByteSizeLong() const {
          const SC_CHAT_BROADCAST& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.SC_CHAT_BROADCAST)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string msg = 2;
            if (!this_._internal_msg().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_msg());
            }
            // uint64 playerId = 1;
            if (this_._internal_playerid() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_playerid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SC_CHAT_BROADCAST::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SC_CHAT_BROADCAST*>(&to_msg);
  auto& from = static_cast<const SC_CHAT_BROADCAST&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SC_CHAT_BROADCAST)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (from._internal_playerid() != 0) {
    _this->_impl_.playerid_ = from._impl_.playerid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SC_CHAT_BROADCAST::CopyFrom(const SC_CHAT_BROADCAST& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SC_CHAT_BROADCAST)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_CHAT_BROADCAST::InternalSwap(SC_CHAT_BROADCAST* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
        swap(_impl_.playerid_, other->_impl_.playerid_);
}

::google::protobuf::Metadata SC_CHAT_BROADCAST::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SC_WHISPER::_Internal {
 public:
};

SC_WHISPER::SC_WHISPER(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.SC_WHISPER)
}
inline PROTOBUF_NDEBUG_INLINE SC_WHISPER::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::SC_WHISPER& from_msg)
      : msg_(arena, from.msg_),
        _cached_size_{0} {}

SC_WHISPER::SC_WHISPER(
    ::google::protobuf::Arena* arena,
    const SC_WHISPER& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SC_WHISPER* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.fromplayerid_ = from._impl_.fromplayerid_;

  // @@protoc_insertion_point(copy_constructor:Protocol.SC_WHISPER)
}
inline PROTOBUF_NDEBUG_INLINE SC_WHISPER::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msg_(arena),
        _cached_size_{0} {}

inline void SC_WHISPER::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.fromplayerid_ = {};
}
SC_WHISPER::~SC_WHISPER() {
  // @@protoc_insertion_point(destructor:Protocol.SC_WHISPER)
  SharedDtor(*this);
}
inline void SC_WHISPER::SharedDtor(MessageLite& self) {
  SC_WHISPER& this_ = static_cast<SC_WHISPER&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.msg_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SC_WHISPER::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SC_WHISPER(arena);
}
constexpr auto SC_WHISPER::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SC_WHISPER),
                                            alignof(SC_WHISPER));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SC_WHISPER::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SC_WHISPER_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SC_WHISPER::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SC_WHISPER>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SC_WHISPER::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SC_WHISPER>(), &SC_WHISPER::ByteSizeLong,
            &SC_WHISPER::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SC_WHISPER, _impl_._cached_size_),
        false,
    },
    &SC_WHISPER::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SC_WHISPER::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 31, 2> SC_WHISPER::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::SC_WHISPER>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SC_WHISPER, _impl_.msg_)}},
    // uint64 fromplayerId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SC_WHISPER, _impl_.fromplayerid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SC_WHISPER, _impl_.fromplayerid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 fromplayerId = 1;
    {PROTOBUF_FIELD_OFFSET(SC_WHISPER, _impl_.fromplayerid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string msg = 2;
    {PROTOBUF_FIELD_OFFSET(SC_WHISPER, _impl_.msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\0\3\0\0\0\0\0"
    "Protocol.SC_WHISPER"
    "msg"
  }},
};

PROTOBUF_NOINLINE void SC_WHISPER::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.SC_WHISPER)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _impl_.fromplayerid_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SC_WHISPER::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SC_WHISPER& this_ = static_cast<const SC_WHISPER&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SC_WHISPER::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SC_WHISPER& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.SC_WHISPER)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 fromplayerId = 1;
          if (this_._internal_fromplayerid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_fromplayerid(), target);
          }

          // string msg = 2;
          if (!this_._internal_msg().empty()) {
            const std::string& _s = this_._internal_msg();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.SC_WHISPER.msg");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.SC_WHISPER)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SC_WHISPER::ByteSizeLong(const MessageLite& base) {
          const SC_WHISPER& this_ = static_cast<const SC_WHISPER&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SC_WHISPER::ByteSizeLong() const {
          const SC_WHISPER& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.SC_WHISPER)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string msg = 2;
            if (!this_._internal_msg().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_msg());
            }
            // uint64 fromplayerId = 1;
            if (this_._internal_fromplayerid() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_fromplayerid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SC_WHISPER::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SC_WHISPER*>(&to_msg);
  auto& from = static_cast<const SC_WHISPER&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.SC_WHISPER)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (from._internal_fromplayerid() != 0) {
    _this->_impl_.fromplayerid_ = from._impl_.fromplayerid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SC_WHISPER::CopyFrom(const SC_WHISPER& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.SC_WHISPER)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SC_WHISPER::InternalSwap(SC_WHISPER* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
        swap(_impl_.fromplayerid_, other->_impl_.fromplayerid_);
}

::google::protobuf::Metadata SC_WHISPER::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CS_WHISPER::_Internal {
 public:
};

CS_WHISPER::CS_WHISPER(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.CS_WHISPER)
}
inline PROTOBUF_NDEBUG_INLINE CS_WHISPER::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Protocol::CS_WHISPER& from_msg)
      : msg_(arena, from.msg_),
        _cached_size_{0} {}

CS_WHISPER::CS_WHISPER(
    ::google::protobuf::Arena* arena,
    const CS_WHISPER& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CS_WHISPER* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.targetplayerid_ = from._impl_.targetplayerid_;

  // @@protoc_insertion_point(copy_constructor:Protocol.CS_WHISPER)
}
inline PROTOBUF_NDEBUG_INLINE CS_WHISPER::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msg_(arena),
        _cached_size_{0} {}

inline void CS_WHISPER::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.targetplayerid_ = {};
}
CS_WHISPER::~CS_WHISPER() {
  // @@protoc_insertion_point(destructor:Protocol.CS_WHISPER)
  SharedDtor(*this);
}
inline void CS_WHISPER::SharedDtor(MessageLite& self) {
  CS_WHISPER& this_ = static_cast<CS_WHISPER&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.msg_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CS_WHISPER::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CS_WHISPER(arena);
}
constexpr auto CS_WHISPER::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CS_WHISPER),
                                            alignof(CS_WHISPER));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CS_WHISPER::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CS_WHISPER_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CS_WHISPER::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CS_WHISPER>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CS_WHISPER::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CS_WHISPER>(), &CS_WHISPER::ByteSizeLong,
            &CS_WHISPER::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CS_WHISPER, _impl_._cached_size_),
        false,
    },
    &CS_WHISPER::kDescriptorMethods,
    &descriptor_table_Protocol_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CS_WHISPER::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 31, 2> CS_WHISPER::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Protocol::CS_WHISPER>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string msg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(CS_WHISPER, _impl_.msg_)}},
    // uint64 targetplayerId = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CS_WHISPER, _impl_.targetplayerid_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(CS_WHISPER, _impl_.targetplayerid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 targetplayerId = 1;
    {PROTOBUF_FIELD_OFFSET(CS_WHISPER, _impl_.targetplayerid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string msg = 2;
    {PROTOBUF_FIELD_OFFSET(CS_WHISPER, _impl_.msg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\0\3\0\0\0\0\0"
    "Protocol.CS_WHISPER"
    "msg"
  }},
};

PROTOBUF_NOINLINE void CS_WHISPER::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.CS_WHISPER)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msg_.ClearToEmpty();
  _impl_.targetplayerid_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CS_WHISPER::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CS_WHISPER& this_ = static_cast<const CS_WHISPER&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CS_WHISPER::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CS_WHISPER& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:Protocol.CS_WHISPER)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 targetplayerId = 1;
          if (this_._internal_targetplayerid() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_targetplayerid(), target);
          }

          // string msg = 2;
          if (!this_._internal_msg().empty()) {
            const std::string& _s = this_._internal_msg();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "Protocol.CS_WHISPER.msg");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:Protocol.CS_WHISPER)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CS_WHISPER::ByteSizeLong(const MessageLite& base) {
          const CS_WHISPER& this_ = static_cast<const CS_WHISPER&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CS_WHISPER::ByteSizeLong() const {
          const CS_WHISPER& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:Protocol.CS_WHISPER)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string msg = 2;
            if (!this_._internal_msg().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_msg());
            }
            // uint64 targetplayerId = 1;
            if (this_._internal_targetplayerid() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_targetplayerid());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CS_WHISPER::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CS_WHISPER*>(&to_msg);
  auto& from = static_cast<const CS_WHISPER&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Protocol.CS_WHISPER)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msg().empty()) {
    _this->_internal_set_msg(from._internal_msg());
  }
  if (from._internal_targetplayerid() != 0) {
    _this->_impl_.targetplayerid_ = from._impl_.targetplayerid_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CS_WHISPER::CopyFrom(const CS_WHISPER& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.CS_WHISPER)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CS_WHISPER::InternalSwap(CS_WHISPER* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msg_, &other->_impl_.msg_, arena);
        swap(_impl_.targetplayerid_, other->_impl_.targetplayerid_);
}

::google::protobuf::Metadata CS_WHISPER::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_Protocol_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
