# -*- coding: utf-8 -*-
import re
import os

def generate():
    proto_path = r"C:\Users\ha052\Desktop\Project-A\Project_TOY_server\Protocol.proto"
    output_path = r"C:\Users\ha052\Desktop\Project-A\Project_TOY_server\PacketHandler.h"

    with open(proto_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # 1. Message 이름들 추출 (데이터 구조)
    messages = re.findall(r'message\s+(\w+)\s*\{', content)
    
    # 2. Enum 값들 추출 (패킷 아이디)
    # enum { ... PKT_CS_LOGIN = 1; ... } 형태를 가정
    packet_enums = re.findall(r'(PKT_\w+)\s*=\s*\d+', content)

    # 3. 코드 조립
    enum_part = "enum : uint16\n{\n"
    handler_decls = ""
    register_part = "inline void PacketHandler::Init()\n{\n"
    register_part += "    for (int32 i = 0; i < 65535; i++) GPacketHandler[i] = Handle_INVALID;\n\n"

    # Enum 리스트를 돌면서 Message와 매칭되는지 확인
    for pkt_enum in packet_enums:
        # Enum 정의 추가
        # (이미 .proto에 enum이 있다면 C++에서는 중복 정의가 될 수 있으니 주의)
        # 만약 .proto의 enum을 그대로 쓰고 싶다면 이 부분은 생략 가능합니다.
        
        # 실제 메시지 이름 추측 (PKT_ 제거)
        msg_name = pkt_enum.replace("PKT_", "")
        
        if msg_name in messages:
            if "CS_" in msg_name:
                # 서버가 처리해야 할 패킷 (수신)
                handler_decls += f"bool Handle_{msg_name}(SessionRef& session, Protocol::{msg_name}& pkt);\n"
                register_part += f"    GPacketHandler[Protocol::PacketId::{pkt_enum}] = [](SessionRef& session, BYTE* buffer, int32 len) {{\n"
                register_part += f"        return HandlePacket<Protocol::{msg_name}>(Handle_{msg_name}, session, buffer, len);\n"
                register_part += f"    }};\n"
            else:
                # SC_ 패킷 등은 수신 핸들러 불필요
                register_part += f"    GPacketHandler[Protocol::PacketId::{pkt_enum}] = Handle_INVALID;\n"

    enum_part += "};"
    register_part += "}"

    # 4. making final file script
    full_content = f"""#pragma once
#include "Protocol/Protocol.pb.h"
#include "Types.h"
#include "ServerUtils.h"

// ----------------------------------------------------------------------------
//  this file is generated by GeneratePacketHandler.py
//  if Fix it manually , it can be update by GeneratePacketHandler.py automatically
// ----------------------------------------------------------------------------

using SessionRef = std::shared_ptr<class Session>;
using PacketHandlerFunc = std::function<bool(SessionRef&, BYTE*, int32)>;
extern PacketHandlerFunc GPacketHandler[65535];

{enum_part}

bool Handle_INVALID(SessionRef& session, BYTE* buffer, int32 len);
{handler_decls}

class PacketHandler
{{
public:
    static void Init();
    static bool HandlePacket(SessionRef& session, BYTE* buffer, int32 len)
    {{
        PacketHeader* header = reinterpret_cast<PacketHeader*>(buffer);
        return GPacketHandler[header->id](session, buffer, len);
    }}

private:
    template<typename T, typename ProcessFunc>
    static bool HandlePacket(ProcessFunc func, SessionRef& session, BYTE* buffer, int32 len)
    {{
        T pkt;
        if (pkt.ParseFromArray(buffer + sizeof(PacketHeader), len - sizeof(PacketHeader)) == false)
            return false;

        return func(session, pkt);
    }}
}};
"""

    # 5. file read and write and add Init implement part 
    full_content += f"\n\n{register_part}"

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(full_content)

    print(f"Success: {output_path} has been updated. (Found {len(messages)} packets)")

if __name__ == "__main__":
    generate()  