#pragma once
#include "Protocol/Protocol.pb.h"
#include "Types.h"
#include "ServerUtils.h"

// ----------------------------------------------------------------------------
//  this file is generated by GeneratePacketHandler.py
//  if Fix it manually , it can be update by GeneratePacketHandler.py automatically
// ----------------------------------------------------------------------------

using SessionRef = std::shared_ptr<class Session>;
using PacketHandlerFunc = std::function<bool(SessionRef&, BYTE*, int32)>;
extern PacketHandlerFunc GPacketHandler[65535];

enum : uint16
{
};

bool Handle_INVALID(SessionRef& session, BYTE* buffer, int32 len);
bool Handle_CS_LOGIN(SessionRef& session, Protocol::CS_LOGIN& pkt);
bool Handle_CS_CHAT(SessionRef& session, Protocol::CS_CHAT& pkt);
bool Handle_CS_WHISPER(SessionRef& session, Protocol::CS_WHISPER& pkt);


class PacketHandler
{
public:
    static void Init();
    static bool HandlePacket(SessionRef& session, BYTE* buffer, int32 len)
    {
        PacketHeader* header = reinterpret_cast<PacketHeader*>(buffer);
        return GPacketHandler[header->id](session, buffer, len);
    }

private:
    template<typename T, typename ProcessFunc>
    static bool HandlePacket(ProcessFunc func, SessionRef& session, BYTE* buffer, int32 len)
    {
        T pkt;
        if (pkt.ParseFromArray(buffer + sizeof(PacketHeader), len - sizeof(PacketHeader)) == false)
            return false;

        return func(session, pkt);
    }
};


inline void PacketHandler::Init()
{
    for (int32 i = 0; i < 65535; i++) GPacketHandler[i] = Handle_INVALID;

    GPacketHandler[Protocol::PacketId::PKT_CS_LOGIN] = [](SessionRef& session, BYTE* buffer, int32 len) {
        return HandlePacket<Protocol::CS_LOGIN>(Handle_CS_LOGIN, session, buffer, len);
    };
    GPacketHandler[Protocol::PacketId::PKT_SC_LOGIN_OK] = Handle_INVALID;
    GPacketHandler[Protocol::PacketId::PKT_CS_CHAT] = [](SessionRef& session, BYTE* buffer, int32 len) {
        return HandlePacket<Protocol::CS_CHAT>(Handle_CS_CHAT, session, buffer, len);
    };
    GPacketHandler[Protocol::PacketId::PKT_SC_CHAT_BROADCAST] = Handle_INVALID;
    GPacketHandler[Protocol::PacketId::PKT_SC_WHISPER] = Handle_INVALID;
    GPacketHandler[Protocol::PacketId::PKT_CS_WHISPER] = [](SessionRef& session, BYTE* buffer, int32 len) {
        return HandlePacket<Protocol::CS_WHISPER>(Handle_CS_WHISPER, session, buffer, len);
    };
}